import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Root Config</title>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta httpEquiv="X-UA-Compatible" content="ie=edge"/>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        {/* This CSP allows any SSL-enabled host and for arbitrary eval(), but you should limit these directives further to increase your app's security.
        Learn more about CSP policies at https://content-security-policy.com/#directive */}
        <meta httpEquiv="Content-Security-Policy" content="img-src 'self' data:; default-src 'self' https: localhost:*; script-src 'unsafe-inline' 'unsafe-eval' https: localhost:*; connect-src https: localhost:* ws://localhost:*; style-src 'unsafe-inline' https:; object-src 'none';"/>
        <meta name="importmap-type" content="systemjs-importmap" />

      </Head>

      {/* Remove this if you only support browsers that support async/await.
      This is needed by babel to share largeish helper code for compiling async/await in older
      browsers. More information at https://github.com/single-spa/create-single-spa/issues/112 */}
      {/* <script src="https://cdn.jsdelivr.net/npm/regenerator-runtime@0.13.7/runtime.min.js"></script> */}

      
      

      {/* If you wish to turn off import-map-overrides for specific environments (prod), uncomment the line below
      More info at https://github.com/joeldenning/import-map-overrides/blob/master/docs/configuration.md#domain-list
      <meta name="import-map-overrides-domains" content="denylist:prod.example.com" /> */}

      {/* Shared dependencies go into this import map. Your shared dependencies must be of one of the following formats:
        1. System.register (preferred when possible) - https://github.com/systemjs/systemjs/blob/master/docs/system-register.md
        2. UMD - https://github.com/umdjs/umd
        3. Global variable

      More information about shared dependencies can be found at https://single-spa.js.org/docs/recommended-setup#sharing-with-import-maps. */}
      
      <link rel="preload" href="https://cdn.jsdelivr.net/npm/single-spa@5.9.0/lib/system/single-spa.min.js" as="script"/>
      {/* <script type="systemjs-importmap" src="/api/import-map"></script> */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>

    </div>
  )
}

export default Home
